apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - persistent-volume-claim.yml
  - persistent-volume.yml
  - deployment.yml
  - service.yml
  - ingress.yml
