apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/md0/docker-config/readarr/config
    server: 10.0.0.150
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/md0/data
    server: 10.0.0.150
  persistentVolumeReclaimPolicy: Retain
