apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/md0/docker-config/data
    server: 10.0.0.150
  persistentVolumeReclaimPolicy: Retain
