additionalArguments:
  # DNS Challenge
  # ---
  # Duckdns Example:
  - --certificatesresolvers.duckdns.acme.dnschallenge.provider=duckdns
  - --certificatesresolvers.duckdns.acme.email=<redacted>
  - --certificatesresolvers.duckdns.acme.storage=/ssl-certs/acme-duckdns.json

logs:
  # Configure log settings here...
  general:
    level: ERROR

ports:
  # Configure your entrypoints here...
  web:
    # Permanent Redirect to HTTPS
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true
      # Set a Default CertResolver
      certResolver: duckdns

env:
  # DNS Challenge Credentials
  # ---
  # Duckdns Example:
  - name: DUCKDNS_TOKEN
    valueFrom:
      secretKeyRef:
        key: token
        name: duckdns-credentials

# Disable Dashboard
ingressRoute:
  dashboard:
    enabled: false

# Persistent Storage
persistence:
  enabled: true
  name: ssl-certs
  size: 1Gi
  path: /ssl-certs

deployment:
  initContainers:
  - name: volume-permissions
    image: busybox:1.36.1
    command:
      - sh
      - -c
      - |
        if [ "$(ls -A /ssl-certs)" ]; then
          chmod -Rv 600 /ssl-certs/*;
        else
          echo "No files in /ssl-certs";
        fi
    volumeMounts:
      - name: ssl-certs
        mountPath: /ssl-certs

# Set Traefik as your default Ingress Controller, according to Kubernetes 1.19+ changes.
ingressClass:
  enabled: true
  isDefaultClass: true
