apiVersion: v1
kind: PersistentVolume
metadata:
  name: homer-assets-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/md0/docker-config/assets
    server: 10.0.0.150
  persistentVolumeReclaimPolicy: Retain