apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-assets-pvc
  namespace: homer
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: homer-assets-pv
  storageClassName: ""