apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyseerr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/md0/docker-config/jellyseerr/config
    server: 10.0.0.150
  persistentVolumeReclaimPolicy: Retain